// Code generated by Axiom CLI; DO NOT EDIT.
//! axiom_context — the single platform-capability surface injected into every
//! node function (ADR-001). A node handler receives `ax: &dyn AxiomContext` and
//! reaches logging, secrets, reflection, and mutation through it.

use std::collections::HashMap;

// ── Logging & secrets ───────────────────────────────────────────────────────

/// Structured logger pre-configured for a single node invocation.
pub trait AxiomLogger: Send + Sync {
    fn debug(&self, msg: &str, attrs: &HashMap<&str, String>);
    fn info(&self, msg: &str, attrs: &HashMap<&str, String>);
    fn warn(&self, msg: &str, attrs: &HashMap<&str, String>);
    fn error(&self, msg: &str, attrs: &HashMap<&str, String>);
}

/// Typed result of `AxiomSecrets::status(name)` — ADR-156.
///
/// `get(name)` alone returns `("", false)` both when a secret was revoked
/// after execution start and when it was never configured at all — a node
/// cannot tell "re-authorize this credential" from "check axiom.yaml" from
/// that result alone. Use `status()` when the distinction matters.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum SecretStatus {
    /// The secret currently resolves to a value; `get(name)` returns it.
    Available,
    /// The secret existed in this execution's initial snapshot but no
    /// longer resolves against the live vault — it was deleted or revoked
    /// after the execution started. `get(name)` returns `("", false)`.
    Revoked,
    /// The secret was never present for this node — never configured by
    /// the tenant, or (for a non-owned node) not authorized. `get(name)`
    /// returns `("", false)`, identically to `Revoked`.
    Unset,
}

/// Read-only access to tenant secrets resolved by the platform.
pub trait AxiomSecrets: Send + Sync {
    /// Returns `(value, true)` when the named secret is present, else `("", false)`.
    fn get(&self, name: &str) -> (String, bool);

    /// Returns the typed status of a declared secret — ADR-156. Distinguishes
    /// `SecretStatus::Revoked` (declared, existed at execution start, no
    /// longer resolvable) from `SecretStatus::Unset` (never configured) — a
    /// distinction `get` alone cannot make since both return `("", false)`.
    ///
    /// ADR-156 (2026-07-20): this is a DEFAULT method, not a required one, so
    /// the accessor stays BACKWARD-COMPATIBLE — a required trait method would
    /// break every existing node's hand-written `AxiomSecrets` test double at
    /// compile time. The platform's `MapSecrets` overrides it with the real
    /// Available/Revoked/Unset distinction; an implementer that only provides
    /// `get` degrades to Available (present) or Unset (absent), never a false
    /// Revoked.
    fn status(&self, name: &str) -> SecretStatus {
        if self.get(name).1 {
            SecretStatus::Available
        } else {
            SecretStatus::Unset
        }
    }
}

// ADR-129 (2026-07-11): agentic memory (ax.agent().memory()) is out of scope
// for beta and has been removed from the node SDK entirely — a shared
// marketplace node's memory proxy stamped the deploy-time publisher tenant,
// letting unrelated tenants composing the same node read each other's memory.
// Removing the client surface here closes the reachable path at compile time.
// The backend (internal/memory, proto/memory, MemoryService) is retained for
// post-beta.

// ── Reflection (ADR-050 / ADR-055) ──────────────────────────────────────────

/// One node placement in the running flow.
#[derive(Clone, Debug, Default)]
pub struct ReflectionNode {
    pub instance_id: u32,
    pub node_ulid: String,
    pub name: String,
    pub package_name: String,
    pub package_version: String,
    pub node_type: String, // "node" | "subflow" | "pipeline"
    pub input_message_name: String,
    pub output_message_name: String,
    pub canvas_node_id: String,
    /// ADR-086: coarse-grid column (flow depth, left->right).
    pub grid_col: i32,
    /// ADR-086: coarse-grid row (parallel lane, top->down).
    pub grid_row: i32,
}

/// Agent-readable digest of an edge's dispatch condition (ADR-055 / GAP-4):
/// e.g. field="tools", op="EQ", operands=["ToolX"] means "ToolX" ∈ tools.
#[derive(Clone, Debug, Default)]
pub struct ConditionSummary {
    pub field: String,
    pub op: String,
    pub operands: Vec<String>,
}

/// One edge (forward or loop) in the running flow. `has_condition`/`has_adapter`
/// are structural flags; `condition_summary` is `Some` only when conditional.
#[derive(Clone, Debug, Default)]
pub struct ReflectionEdge {
    pub src_instance: u32,
    pub dst_instance: u32,
    pub canvas_edge_id: String,
    pub has_condition: bool,
    pub has_adapter: bool,
    pub max_iterations: u32,
    pub condition_summary: Option<ConditionSummary>,
}

/// Where the current invocation sits in the running flow.
#[derive(Clone, Debug, Default)]
pub struct FlowPosition {
    pub current_instance: u32,
    pub depth: u32,
    pub loop_iterations: HashMap<u32, u32>,
    pub subflow_stack_graph_ids: Vec<String>,
}

/// Read-only view of the running flow graph + position.
/// Obtain via `ax.reflection().flow()`.
pub trait FlowReflection: Send + Sync {
    fn nodes(&self) -> &[ReflectionNode];
    fn edges(&self) -> &[ReflectionEdge];
    fn loop_edges(&self) -> &[ReflectionEdge];
    fn position(&self) -> &FlowPosition;
    fn graph_id(&self) -> &str;
}

/// Reflection capability bundle. Today exposes only `flow()`.
pub trait Reflection: Send + Sync {
    fn flow(&self) -> &dyn FlowReflection;
}

// ── Mutation (ADR-051 / ADR-054) ────────────────────────────────────────────

/// Optional structural predicate gating a mutation-added edge (ADR-054 / GAP-1).
/// {op:"EQ", field:"tools", value:"ToolX"} expresses "ToolX" in tools.
#[derive(Clone, Debug, Default)]
pub struct EdgeCondition {
    pub op: String,
    pub field: String,
    pub value: String,
}

/// Optional canvas placement hint for an added node.
#[derive(Clone, Copy, Debug, Default)]
pub struct CanvasPosition {
    pub x: f64,
    pub y: f64,
    /// ADR-086: coarse-grid cell. When set (non-zero), the worker places the
    /// node at this cell and derives pixels; grid takes precedence over x/y.
    pub grid_col: i32,
    pub grid_row: i32,
}

/// Append-only mutation surface for the running flow. `add_node` returns the
/// batch-local instance id; use it on subsequent `add_edge` calls.
pub trait FlowMutation: Send + Sync {
    fn add_node(&self, package_name: &str, package_version: &str, canvas_position: Option<CanvasPosition>) -> u32;
    /// Wire src→dst. `Some(condition)` for a conditional dispatch edge (ADR-054);
    /// `None` for an unconditional edge (v1).
    fn add_edge(&self, src_instance: u32, dst_instance: u32, condition: Option<EdgeCondition>);
}

/// Mutation capability bundle. Today exposes only `flow()`.
pub trait Mutation: Send + Sync {
    fn flow(&self) -> &dyn FlowMutation;
}

// ── Telemetry (ADR-073) ──────────────────────────────────────────────────────

/// A typed telemetry attribute. Build one with `attr_str`/`attr_int`/
/// `attr_float`/`attr_bool`. `value` holds one variant of `AttrValue`.
#[derive(Clone, Debug)]
pub struct Attr {
    pub key: String,
    pub value: AttrValue,
}

/// The safe subset of attribute value types accepted by the telemetry surface.
#[derive(Clone, Debug)]
pub enum AttrValue {
    Str(String),
    Int(i64),
    Float(f64),
    Bool(bool),
}

/// Construct a typed telemetry `Attr`.
pub fn attr_str(key: &str, value: &str) -> Attr {
    Attr { key: key.to_string(), value: AttrValue::Str(value.to_string()) }
}
pub fn attr_int(key: &str, value: i64) -> Attr {
    Attr { key: key.to_string(), value: AttrValue::Int(value) }
}
pub fn attr_float(key: &str, value: f64) -> Attr {
    Attr { key: key.to_string(), value: AttrValue::Float(value) }
}
pub fn attr_bool(key: &str, value: bool) -> Attr {
    Attr { key: key.to_string(), value: AttrValue::Bool(value) }
}

/// AxiomTelemetry — the tenant-safe node telemetry surface (ADR-073). Every call
/// buffers in-process and is flushed to the sidecar on handler return; the
/// sidecar is the SOLE collector egress and stamps tenant/flow/trace context, so
/// node code can nest telemetry under node.invoke but cannot forge tenant
/// identity or reach the collector directly. Under `axiom dev` (no sidecar) it
/// degrades to a no-op, exactly like the logger.
pub trait AxiomTelemetry: Send + Sync {
    /// Record a named event (with optional attributes) on the invocation span.
    fn add_event(&self, name: &str, attrs: &[Attr]);
    /// Add `value` to a named custom counter.
    fn counter(&self, name: &str, value: f64, attrs: &[Attr]);
    /// Record `value` into a named custom histogram.
    fn histogram(&self, name: &str, value: f64, attrs: &[Attr]);
}

/// No-op telemetry used under `axiom dev` / unit tests, where no sidecar is
/// present. Mirrors how the logger degrades when off-platform.
pub struct NoopTelemetry;
impl AxiomTelemetry for NoopTelemetry {
    fn add_event(&self, _name: &str, _attrs: &[Attr]) {}
    fn counter(&self, _name: &str, _value: f64, _attrs: &[Attr]) {}
    fn histogram(&self, _name: &str, _value: f64, _attrs: &[Attr]) {}
}

// ── The injection point ─────────────────────────────────────────────────────

/// AxiomContext — the single platform-capability surface for one invocation.
/// Passed as `ax: &dyn AxiomContext` to every node handler.
pub trait AxiomContext: Send + Sync {
    fn log(&self) -> &dyn AxiomLogger;
    fn secrets(&self) -> &dyn AxiomSecrets;
    fn execution_id(&self) -> &str;
    fn flow_id(&self) -> &str;
    fn tenant_id(&self) -> &str;
    /// Flow reflection — `ax.reflection().flow()` (ADR-050).
    fn reflection(&self) -> &dyn Reflection;
    /// Mid-execution mutation — `ax.mutation().flow()` (ADR-051).
    fn mutation(&self) -> &dyn Mutation;

    /// ADR-073 (2026-06-09): tenant-safe telemetry carrier. This is a
    /// DEFAULT method — it returns `None`, so existing committed test doubles
    /// that `impl AxiomContext` keep compiling unchanged (NON-BREAKING). The
    /// production `AxiomContextImpl` overrides it to expose its per-invocation
    /// buffer; `telemetry_of(ax)` reads through it. Node authors should not
    /// implement this directly — use `ax.telemetry()` via `telemetry_of`.
    fn axiom_telemetry(&self) -> Option<&dyn AxiomTelemetry> {
        None
    }
}

/// Return the tenant-safe telemetry surface for this invocation (ADR-073). This
/// is a FREE function rather than a required `AxiomContext` method on purpose:
/// adding a required method would break every committed test double. In
/// production the concrete context exposes a real buffer (flushed to the sidecar,
/// the sole collector egress); under `axiom dev` / unit tests it degrades to a
/// no-op.
///
/// ```ignore
/// telemetry_of(ax).add_event("cache_hit", &[attr_int("size", 42)]);
/// ```
pub fn telemetry_of(ax: &dyn AxiomContext) -> &dyn AxiomTelemetry {
    static NOOP: NoopTelemetry = NoopTelemetry;
    ax.axiom_telemetry().unwrap_or(&NOOP)
}
